### PR TITLE
XGBoost - Documentation

### PR DESCRIPTION
**Pull request by hritikchaturvedi11**
added XGboost description in Readme.md file

### CODE REVIEW

**Comment by hritikchaturvedi11** [comment]
Issue #67 
Assigned to me, please check it out.

**Comment by hritikchaturvedi11** [comment]
@geekquad kindly review my documentation for issue #67. So I can move forward to other issues that have been assigned to me.

**Comment by ashwani-rathee** [comment]
@hritikchaturvedi11 I don't know what to do with this PR since you haven't yet updated the code as per the instructions.

**Comment by ashwani-rathee** [comment]
Invalid since no update from your side @hritikchaturvedi11 
@geekquad What to do?

**Comment by snehasharma76** [comment]
Is it still open? I would like to work on this one. It would be nice if you tell me what all is required?

**Pull request closed without merging**
