### PR TITLE
Cross-Validation-from-Scratch #114

### PR DESCRIPTION
**Pull request by Dishita2602**
I have code for 4 methods involved for cross validation.
Leave One Out (Linear Reg)
Leave P Out (Linear Reg)
K fold (Log Reg)
K Stratifiedfold (Log Reg)

Please review it.

(Sorry it's issue #114 )

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
Not a class type implementation, @Dishita2602 Please add a class type implementation

**Comment by Dishita2602** [comment]
> Not a class type implementation, @Dishita2602 Please add a class type implementation

Can you please be more clearer ?

**Comment by geekquad** [comment]
Hey @Dishita2602, 
please go through the Contributing Guidelines.
We need a class-type implementation of the algorithm/technique from scratch using nothing but NymPy.
No external modules/libraries are allowed. 
To know more about classes in Python please refer [here](https://docs.python.org/3/tutorial/classes.html).

**Comment by Dishita2602** [comment]
> Hey @Dishita2602,
> please go through the Contributing Guidelines.
> We need a class-type implementation of the algorithm/technique from scratch using nothing but NymPy.
> No external modules/libraries are allowed.
> To know more about classes in Python please refer [here](https://docs.python.org/3/tutorial/classes.html).

Issue was not created by me so I was not knowing that you guys are only looking for cross-validation implementation without any libraries. Also I had commented in issue that I am going to use these 4 methods but nobody replied to it. That's why I did PR as per my understanding.

**Comment by geekquad** [comment]
> > Hey @Dishita2602,
> > please go through the Contributing Guidelines.
> > We need a class-type implementation of the algorithm/technique from scratch using nothing but NymPy.
> > No external modules/libraries are allowed.
> > To know more about classes in Python please refer [here](https://docs.python.org/3/tutorial/classes.html).
> 
> Issue was not created by me so I was not knowing that you guys are only looking for cross-validation implementation without any libraries. Also I had commented in issue that I am going to use these 4 methods but nobody replied to it. That's why I did PR as per my understanding.

Hey @Dishita2602,
we might have missed that, apologies. But we have mentioned everything in the Contributing Guidelines. 
Please make the amendments in the current code-base. Thank you.

**Comment by geekquad** [comment]
Hey @Dishita2602, you willing to complete it?

**Comment by ashwani-rathee** [comment]
This doesn't follow the contributing guidelines mentioned and PR creatrr is inactive. Hence closing this PR

**Pull request closed without merging**
