### PR TITLE
Adaboost-Base Issue#35

### PR DESCRIPTION
**Pull request by skybluee2001**
Implementation of the Adaboost with Decision Tree & SVC as Base Estimators
Issue#35

### CODE REVIEW

**Comment by skybluee2001** [comment]
@ashwani-rathee Kindly review the PR.

**Comment by ashwani-rathee** [comment]
@skybluee2001 Please check the readme.md and contribution guidelines.We don't accept algorithms in .ipynb format.You have to submit the algorithm in .py format.

**Comment by skybluee2001** [comment]
@ashwani-rathee I am not able to read the entire Contribution Guidelines as it is giving a 404 error. I have added my file in the .py format. Kindly review it.

**Comment by ashwani-rathee** [comment]
@skybluee2001 You have to implement Adaboost from scratch not import it from sklearn/scikit etc.Please update it

**Comment by skybluee2001** [comment]
@ashwani-rathee, okay, I understood my mistake. I will update it.

**Comment by skybluee2001** [comment]
@ashwani-rathee, I have updated the code. Kindly review it.

**Comment by ashwani-rathee** [comment]
@skybluee2001 Good job there,0.92 accuracy for both direct and implemented model...you can comment out the test code (the one that uses sklearn and make it clean.Otherwise,it looks good to me @geekquad

**Comment by skybluee2001** [comment]
@ashwani-rathee, so shall I remove the part under the head "TEST ALGORITHM" and the theory part. Please could you clarify.

**Comment by ashwani-rathee** [comment]
@skybluee2001 Just comment it out for now :)

**Comment by skybluee2001** [comment]
@ashwani-rathee I have commented out the test code. Kindly review it. Thanks for letting me work on this issue :)

**Comment by skybluee2001** [comment]
@ashwani-rathee I have commented out the test code and cleaned it. Kindly review it.

**Comment by skybluee2001** [comment]
@geekquad Kindly review and merge my PR.

**Comment by skybluee2001** [comment]
@ashwani-rathee, if no further changes are required, please add the Clear-M label so that it can get merged.

**Comment by ashwani-rathee** [comment]
Please comment out the testing code @skybluee2001

**Comment by ashwani-rathee** [comment]
Looks good to me @geekquad what do you think?

**Review by geekquad — APPROVED** [review]
Amazing work @skybluee2001.

**Comment by skybluee2001** [comment]
> Amazing work @skybluee2001.

Thank you :)

**Pull request merged**
