### PR TITLE
KNN Base model 

### PR DESCRIPTION
**Pull request by Abheeshth**
I have added kNN base model file please let me know if there are any changes I should do 
@ashwani-rathee 
issue #26

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
@Abheeshth Can you provide a example for testing in the comment,will be helpful for soemone using this later

**Comment by Abheeshth** [comment]
> @Abheeshth Can you provide a example for testing in the comment,will be helpful for someone using this later

Sure I will do that as soon as possible

**Comment by Abheeshth** [comment]
I have  provided a example for testing in the comments. please have a look

**Review by geekquad — APPROVED** [review]
Hey @Abheeshth, amazing work!

**Pull request merged**
