### PR TITLE
added decision tree implementation

### PR DESCRIPTION
**Pull request by ayush237**

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
@ayush237 we are not looking for ipynb implementation.Please read the guidelines and update accordingly.Submit in .py file where we have implementation from scratch (with just numpy) and is in class like format.

**Comment by asimaries** [comment]
Can I do that? its comptele

**Comment by ashwani-rathee** [comment]
This needs to be closed too since no updates

**Comment by asimaries** [comment]
hey I can do that for you its complete
I have done that for the random forest it will work fine here too I guess

**Pull request closed without merging**
