### PR TITLE
Apriori Base issue#36

### PR DESCRIPTION
**Pull request by anjiii-18**
Implementation of Apriori Algorithm (Issue #36)

### CODE REVIEW

**Comment by anjiii-18** [comment]
@ashwani-rathee  Please review my pull request #100.

**Comment by ashwani-rathee** [comment]
@anjiii-18 You would need to give a class type implementation of algorithms so that it can be used later.#64 #11 #44 are good examples of proper implementation by your fellow participants.and also try to keep the code clean,there is a lot of unneccessary content in code.

**Comment by anjiii-18** [comment]
@ashwani-rathee I understood your point and will do the required changes.

**Comment by anjiii-18** [comment]
@ashwani-rathee I updated the code, kindly review it.

**Comment by ashwani-rathee** [comment]
@anjiii-18 the issue now is that whenever you will import the code from apriori,all the other code from apriori base willl also be run(the dataset part) so just keep the class and the import
Other than that,it works just fine on test..just tidy up the code, and its almost ready to be merged :)

**Comment by anjiii-18** [comment]
@ashwani-rathee So shall I comment the test algorithm? I am little confused about changes to be done.

**Comment by anjiii-18** [comment]
@ashwani-rathee or shall I remove the definition and textual part.
It would be great if you could clarify.

**Comment by ashwani-rathee** [comment]
@anjiii-18 just comment it out for now.

**Comment by ashwani-rathee** [comment]
@anjiii-18 Looks good to me @geekquad What do you think?

**Comment by anjiii-18** [comment]
@ashwani-rathee sure. Thanks , I will just do it. :)

**Comment by anjiii-18** [comment]
@ashwani-rathee I have done the commenting part.
Thanks a lot for giving me this project. I will always be grateful to you. :)

**Review by geekquad — APPROVED** [review]
Excellent work @anjiii-18.

**Pull request merged**
