### PR TITLE
Markov's Chain Documentation

### LINKED ISSUE #201: Markov's Chain Documentation
I have added codebase related to Markov's Chain. Now I would like to add documentation related to it. @geekquad

### PR DESCRIPTION
**Pull request by Dishita2602**
Please review it.
fixes #201

### CODE REVIEW

**Review by geekquad — CHANGES_REQUESTED** [review]
```Markov's Chain/Markov's Chain```
This file has no extension.

**Comment by Dishita2602** [comment]
> `Markov's Chain/Markov's Chain`
> This file has no extension.

Can I again send it. I don't know how it happened ?

**Comment by geekquad** [comment]
Yes @Dishita2602, you can make the changes till 5th.

**Comment by geekquad** [comment]
Hey @Dishita2602, are you going to make the changes?

**Comment by Dishita2602** [comment]
Yes !

**Comment by Dishita2602** [comment]
@geekquad I have edited readme file please check it

**Comment by Dishita2602** [comment]
@geekquad I have done change please review my PR asap

**Comment by geekquad** [comment]
No changes have been made @Dishita2602.

**Comment by Dishita2602** [comment]
> No changes have been made @Dishita2602.

Please check now

**Review by geekquad — CHANGES_REQUESTED** [review]
image
You have not added the extension to the Readme file.

**Comment by Dishita2602** [comment]
image
Now done

**Review by geekquad — APPROVED** [review]

**Pull request merged**
