### PR TITLE
Logistic regression - Base issue#38

### PR DESCRIPTION
**Pull request by AkanchhaBhadani**

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
@AkanchhaBhadani You would need to give a class type implementation of algorithms so that it can be used later.#64 #11 #44 are good examples of proper implementation by your fellow participants.Also add code documentation(in .py file itself) of example on how to test it.

**Comment by AkanchhaBhadani** [comment]
OK. Would do it.

**Comment by AkanchhaBhadani** [comment]
> 
> 
> @AkanchhaBhadani You would need to give a class type implementation of algorithms so that it can be used later.#64 #11 #44 are good examples of proper implementation by your fellow participants.Also add code documentation(in .py file itself) of example on how to test it.

Done the implementation. Please let me know if there is still any issue.

**Comment by ashwani-rathee** [comment]
@AkanchhaBhadani Looks good to me @geekquad what do you think?,should we remove the commented out part?

**Review by geekquad — APPROVED** [review]
Amazing work @AkanchhaBhadani.

**Pull request merged**
