### PR TITLE
code for gradient descent

### PR DESCRIPTION
**Pull request by Sibasish-Padhy**
i have written a code for batch gradient descent and have tried to explain the same.please have a look through it and suggest for some changes @ashwani-rathee sir

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
we just need gradient descent implementation @Sibasish-Padhy ,it shouldn't add so many files in repo

**Comment by Sibasish-Padhy** [comment]
okay sir

**Comment by geekquad** [comment]
Hey @Sibasish-Padhy, you have changed 5000+ files. 
image

Please remove the unnecessary files. We just need the code in ```.py```.

**Comment by Sibasish-Padhy** [comment]
sure sir

**Comment by Sibasish-Padhy** [comment]
@geekquad  can you please check once i have probably deleted the unnecessary files.If not please help inform me about the same

**Comment by Sibasish-Padhy** [comment]
also a bit of help can be grateful

**Comment by geekquad** [comment]
Hey @Sibasish-Padhy, the files are still there.
And yes, let me know how can I help you? You can also ping me on the discord server. 
Username: ```Geekquad#0299```

**Comment by ashwani-rathee** [comment]
No update in past 7 days @Sibasish-Padhy. Should we close this?

**Comment by Sibasish-Padhy** [comment]
@ashwani-rathee sir you can assign the issue to someone else....I have rcovered from illness right now

**Pull request closed without merging**
