### PR TITLE
LOWESS REGRESSION SOLUTION #33  

### PR DESCRIPTION
**Pull request by earnsans**
This is the code for Lowess Regression(Locally Weighted Regression)
Issue (https://github.com/Algo-Phantoms/Algo-ScriptML/issues/33?_pjax=%23js-repo-pjax-container)
Kindly review it.

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
@earnsans Please an example on its usage in doc string

**Comment by earnsans** [comment]
@ashwani-rathee  sir I have added an example on it's usage in doc strings at the end of the code.
Please review it.

**Comment by earnsans** [comment]
@ashwani-rathee  sir could you please review it?

**Review by geekquad — APPROVED** [review]
Hey @earnsans, amazing work.

**Comment by earnsans** [comment]
@geekquad thank you sir :)

**Pull request merged**
