### PR TITLE
Bayesian Linear Regression

### PR DESCRIPTION
**Pull request by goelesha**
Please review this PR @ashwani-rathee 
It solves issue  #29 

I have taken reference from the following links:
https://github.com/WillKoehrsen/Data-Analysis/blob/master/bayesian_lr/Bayesian%20Linear%20Regression%20Project.ipynb
https://github.com/zjost/bayesian-linear-regression/blob/master/src/bayes-regression.ipynb

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
@goelesha we don't accept .ipynb implmentation,please submit a .py class type implmentation

**Comment by goelesha** [comment]
@ashwani-rathee I have deleted the jupyter notebook and added a python file instead of that. Kindly review and merge this PR.

**Comment by goelesha** [comment]
@ashwani-rathee Pls merge this PR

**Comment by goelesha** [comment]
@ashwani-rathee Done the class type implementation in the .py file.

Pls merge this PR

**Review by geekquad — APPROVED** [review]
Hey @goelesha, good work!

**Pull request merged**
