### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aanchalsethi**

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
Hey @aanchalsethi , can you add advantages,disadvantages and some references? Other than that this looks good

**Comment by aanchalsethi** [comment]
Okay sure sir, I will update it soon.

**Comment by geekquad** [comment]
Hey @aanchalsethi, any progress?

**Comment by aanchalsethi** [comment]
> Hey @aanchalsethi, any progress?

Yes Sir, Please go through the changes and let me know if you need anything.

**Review by geekquad — APPROVED** [review]
Hey @aanchalsethi, amazing work!

**Comment by aanchalsethi** [comment]
Thankyou sir!

**Pull request merged**
