### PR TITLE
Elastic net - Base

### PR DESCRIPTION
**Pull request by sal-glitch**

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
@sal-glitch  Please check the readme.md and contribution guidelines.We don't accept algorithms in .ipynb format.You have to submit the algorithm in .py format.

**Comment by sal-glitch** [comment]
@ashwani-rathee Sorry about that, I will make another commit in .py format

**Comment by sal-glitch** [comment]
@ashwani-rathee can you review it again. I have changed it to .py format. Thank you!

**Comment by ashwani-rathee** [comment]
@geekquad Looks good to me
@sal-glitch Can you comment out the main() where testing of the algorithm is done

**Comment by sal-glitch** [comment]
@ashwani-rathee Hey I have commented out the main()

**Review by geekquad — APPROVED** [review]
Hey @sal-glitch,
amazing work!

**Pull request merged**
