### PR TITLE
KNN on iris dataset

### PR DESCRIPTION
**Pull request by saumyasinghz**
Simple code for KNN on iris dataset from UCI machine learning repository.

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
@saumyasinghz This generally looks good and is a good example
Though it's very narrow and focussed on IRIS only,would have appreciated a class-type implementation of the method more but got to check with @geekquad

**Comment by saumyasinghz** [comment]
Okay, then you can merge this as data-based and I will create one more pull request based on class type implementation.

**Comment by ashwani-rathee** [comment]
@geekquad can you clarify on this whether we need this or not?Since we need class type implementation only

**Comment by geekquad** [comment]
Certainly not @ashwani-rathee.
Hey @saumyasinghz, please go through the Contributing Guidelines.
We need a class-type implementation of the algorithm/technique from scratch using nothing but NymPy, focusing more on the implementation and not on the application. 
No external modules/libraries are allowed.
To know more about classes in Python please refer here.

**Pull request closed without merging**
