### PR TITLE
Create Neural Network- Documentation

### PR DESCRIPTION
**Pull request by aanchalsethi**

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
@aanchalsethi can you add references? this looks good to me @geekquad

**Comment by aanchalsethi** [comment]
Yes sure for more i will video links in it. Thankyou sir.

**Review by geekquad — CHANGES_REQUESTED** [review]
Hey @aanchalsethi, 
please add the appropriate extension to the file.
Thankyou.

**Comment by aanchalsethi** [comment]
Sir there is no folder for neural networks yet.

**Pull request closed without merging**
