### PR TITLE
Naïve Bayes Algorithm Added

### PR DESCRIPTION
**Pull request by Manasi2001**
I've added the code for implementing Naïve Bayes algorithm from scratch. This PR is with reference to issue #176. @geekquad please check this out.

### CODE REVIEW

**Comment by geekquad** [comment]
Wait for 5 days. If the PR is not made, this code will be reviewed.

**Comment by Manasi2001** [comment]
> Wait for 5 days. If the PR is not made, this code will be reviewed.

May I know the reason behind assigning it to a person who raised the issue 10 days after me @geekquad?
image

**Comment by geekquad** [comment]
> > Wait for 5 days. If the PR is not made, this code will be reviewed.
> 
> May I know the reason behind assigning it to a person who raised the issue 10 days after me @geekquad?
> image

Sure @Manasi2001, 

The issue was raised on ```16th April 2021```.
image


You opened the issue ```13 days``` ago (i.e around ```6th May, 2021```) 
image

#### We assign issues following FICFS.

Please let me know if I am mistaken.

**Comment by Manasi2001** [comment]
> > > Wait for 5 days. If the PR is not made, this code will be reviewed.
> > 
> > 
> > May I know the reason behind assigning it to a person who raised the issue 10 days after me @geekquad?
> > image
> 
> Sure @Manasi2001,
> 
> The issue was raised on `16th April 2021`.
> image
> 
> You opened the issue `13 days` ago (i.e around `6th May, 2021`)
> image
> 
> #### We assign issues following FICFS.
> Please let me know if I am mistaken.

I'm so sorry. I got messed up between months. My bad. 
Apologies 😔

**Comment by Manasi2001** [comment]
Please review this today @geekquad. 5 days are up now. Thanks in advance!

**Pull request merged**
