### PR TITLE
Logistic Regression - Documentation

### PR DESCRIPTION
**Pull request by sakshi012000**

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
@sakshi012000 clean detailed work,some things to update though
- Please add some references for further reading and link to some youtube videos
- Add advantages,disadvantages and applications 
easy peasy,then it would be ready for a merge

**Comment by sakshi012000** [comment]
@ashwani-rathee okay sure , I will do that

**Comment by sakshi012000** [comment]
@ashwani-rathee I have done the editing. Please inform for any other modification if required.

**Comment by ashwani-rathee** [comment]
@sakshi012000 Good work there!! @geekquad What do you think?

**Comment by sakshi012000** [comment]
@ashwani-rathee  can you please kindly merge my PR if no further change is required and inform me if any change is required I will do it.
Thank you

**Review by geekquad — APPROVED** [review]
Good job @sakshi012000.

**Pull request merged**
