### PR TITLE
Perceptron Issue #34

### PR DESCRIPTION
**Pull request by aakriti1318**
This script is based on a deep understanding of Neural Networks and Perceptron with proper explanation and code.

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
@aakriti1318  Please check the readme.md and contribution guidelines.We don't accept algorithms in .ipynb format.You have to submit the algorithm in .py format.

**Comment by ashwani-rathee** [comment]
@aakriti1318 The algorithm does what it's supposed to do just fine and is quite clean with proper documentation imo,but I would need perceptron class type implementation.So that your implementation of the perceptron can be imported by someone else in future and used.#64 #11 #44 are good examples of proper implementation by your fellow participants

**Comment by ashwani-rathee** [comment]
@aakriti1318 I have reviewed it. Please update the base

**Comment by aakriti1318** [comment]
I have updated my script as recommended.

**Comment by ashwani-rathee** [comment]
@aakriti1318 Looks good to me @geekquad

**Comment by aakriti1318** [comment]
Is there anything to change? And when you will merge this PR?

**Review by geekquad — APPROVED** [review]
Amazing work @aakriti1318.

**Pull request merged**
